// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: internal.proto

package gnpb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	_ "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 运行状态
type RunStatus int32

const (
	RunStatus_Unknown    RunStatus = 0  // 未知
	RunStatus_NotRunning RunStatus = 2  // 未运行
	RunStatus_Running    RunStatus = 4  // 运行中
	RunStatus_Success    RunStatus = 8  // 运行成功
	RunStatus_Fail       RunStatus = 16 // 运行失败
	RunStatus_Cancel     RunStatus = 32 // 已取消
	RunStatus_Skip       RunStatus = 64 // 跳过
)

// Enum value maps for RunStatus.
var (
	RunStatus_name = map[int32]string{
		0:  "Unknown",
		2:  "NotRunning",
		4:  "Running",
		8:  "Success",
		16: "Fail",
		32: "Cancel",
		64: "Skip",
	}
	RunStatus_value = map[string]int32{
		"Unknown":    0,
		"NotRunning": 2,
		"Running":    4,
		"Success":    8,
		"Fail":       16,
		"Cancel":     32,
		"Skip":       64,
	}
)

func (x RunStatus) Enum() *RunStatus {
	p := new(RunStatus)
	*p = x
	return p
}

func (x RunStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_enumTypes[0].Descriptor()
}

func (RunStatus) Type() protoreflect.EnumType {
	return &file_internal_proto_enumTypes[0]
}

func (x RunStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunStatus.Descriptor instead.
func (RunStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{0}
}

// 关系类型
type RelationType int32

const (
	RelationType_RT_Unknown RelationType = 0 // 未知
	RelationType_UP         RelationType = 1 // 上
	RelationType_DOWN       RelationType = 2 // 下
	RelationType_CURRENT    RelationType = 3 // 当前
)

// Enum value maps for RelationType.
var (
	RelationType_name = map[int32]string{
		0: "RT_Unknown",
		1: "UP",
		2: "DOWN",
		3: "CURRENT",
	}
	RelationType_value = map[string]int32{
		"RT_Unknown": 0,
		"UP":         1,
		"DOWN":       2,
		"CURRENT":    3,
	}
)

func (x RelationType) Enum() *RelationType {
	p := new(RelationType)
	*p = x
	return p
}

func (x RelationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelationType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_enumTypes[1].Descriptor()
}

func (RelationType) Type() protoreflect.EnumType {
	return &file_internal_proto_enumTypes[1]
}

func (x RelationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelationType.Descriptor instead.
func (RelationType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{1}
}

type GetPayloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayloadRequest) Reset() {
	*x = GetPayloadRequest{}
	mi := &file_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayloadRequest) ProtoMessage() {}

func (x *GetPayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayloadRequest.ProtoReflect.Descriptor instead.
func (*GetPayloadRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{0}
}

func (x *GetPayloadRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dsn           string                 `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayloadResponse) Reset() {
	*x = GetPayloadResponse{}
	mi := &file_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayloadResponse) ProtoMessage() {}

func (x *GetPayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayloadResponse.ProtoReflect.Descriptor instead.
func (*GetPayloadResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{1}
}

func (x *GetPayloadResponse) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *GetPayloadResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type LifecycleEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RunStatus     RunStatus              `protobuf:"varint,2,opt,name=run_status,json=runStatus,proto3,enum=gnpb.RunStatus" json:"run_status,omitempty"`
	Msg           *string                `protobuf:"bytes,3,opt,name=msg,proto3,oneof" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifecycleEventRequest) Reset() {
	*x = LifecycleEventRequest{}
	mi := &file_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleEventRequest) ProtoMessage() {}

func (x *LifecycleEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleEventRequest.ProtoReflect.Descriptor instead.
func (*LifecycleEventRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{2}
}

func (x *LifecycleEventRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LifecycleEventRequest) GetRunStatus() RunStatus {
	if x != nil {
		return x.RunStatus
	}
	return RunStatus_Unknown
}

func (x *LifecycleEventRequest) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

type LifecycleEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifecycleEventResponse) Reset() {
	*x = LifecycleEventResponse{}
	mi := &file_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleEventResponse) ProtoMessage() {}

func (x *LifecycleEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleEventResponse.ProtoReflect.Descriptor instead.
func (*LifecycleEventResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{3}
}

type RelationElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 表ID
	SchemaName    string                 `protobuf:"bytes,2,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"` // schema
	TableName     string                 `protobuf:"bytes,3,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`    // 表名
	TableHash     string                 `protobuf:"bytes,4,opt,name=table_hash,json=tableHash,proto3" json:"table_hash,omitempty"`    // 表hash
	ColumnName    string                 `protobuf:"bytes,5,opt,name=column_name,json=columnName,proto3" json:"column_name,omitempty"` // 字段名
	ColumnHash    string                 `protobuf:"bytes,6,opt,name=column_hash,json=columnHash,proto3" json:"column_hash,omitempty"` // 字段hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationElement) Reset() {
	*x = RelationElement{}
	mi := &file_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationElement) ProtoMessage() {}

func (x *RelationElement) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationElement.ProtoReflect.Descriptor instead.
func (*RelationElement) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{4}
}

func (x *RelationElement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RelationElement) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *RelationElement) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *RelationElement) GetTableHash() string {
	if x != nil {
		return x.TableHash
	}
	return ""
}

func (x *RelationElement) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *RelationElement) GetColumnHash() string {
	if x != nil {
		return x.ColumnHash
	}
	return ""
}

type TableRelation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*RelationElement     `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	Targets       []*RelationElement     `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableRelation) Reset() {
	*x = TableRelation{}
	mi := &file_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableRelation) ProtoMessage() {}

func (x *TableRelation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableRelation.ProtoReflect.Descriptor instead.
func (*TableRelation) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{5}
}

func (x *TableRelation) GetSources() []*RelationElement {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *TableRelation) GetTargets() []*RelationElement {
	if x != nil {
		return x.Targets
	}
	return nil
}

var File_internal_proto protoreflect.FileDescriptor

const file_internal_proto_rawDesc = "" +
	"\n" +
	"\x0einternal.proto\x12\x04gnpb\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/protobuf/any.proto\x1a google/protobuf/descriptor.proto\x1a\x17validate/validate.proto\"#\n" +
	"\x11GetPayloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"@\n" +
	"\x12GetPayloadResponse\x12\x10\n" +
	"\x03dsn\x18\x01 \x01(\tR\x03dsn\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"v\n" +
	"\x15LifecycleEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12.\n" +
	"\n" +
	"run_status\x18\x02 \x01(\x0e2\x0f.gnpb.RunStatusR\trunStatus\x12\x15\n" +
	"\x03msg\x18\x03 \x01(\tH\x00R\x03msg\x88\x01\x01B\x06\n" +
	"\x04_msg\"\x18\n" +
	"\x16LifecycleEventResponse\"\xc2\x01\n" +
	"\x0fRelationElement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vschema_name\x18\x02 \x01(\tR\n" +
	"schemaName\x12\x1d\n" +
	"\n" +
	"table_name\x18\x03 \x01(\tR\ttableName\x12\x1d\n" +
	"\n" +
	"table_hash\x18\x04 \x01(\tR\ttableHash\x12\x1f\n" +
	"\vcolumn_name\x18\x05 \x01(\tR\n" +
	"columnName\x12\x1f\n" +
	"\vcolumn_hash\x18\x06 \x01(\tR\n" +
	"columnHash\"q\n" +
	"\rTableRelation\x12/\n" +
	"\asources\x18\x01 \x03(\v2\x15.gnpb.RelationElementR\asources\x12/\n" +
	"\atargets\x18\x02 \x03(\v2\x15.gnpb.RelationElementR\atargets*b\n" +
	"\tRunStatus\x12\v\n" +
	"\aUnknown\x10\x00\x12\x0e\n" +
	"\n" +
	"NotRunning\x10\x02\x12\v\n" +
	"\aRunning\x10\x04\x12\v\n" +
	"\aSuccess\x10\b\x12\b\n" +
	"\x04Fail\x10\x10\x12\n" +
	"\n" +
	"\x06Cancel\x10 \x12\b\n" +
	"\x04Skip\x10@*=\n" +
	"\fRelationType\x12\x0e\n" +
	"\n" +
	"RT_Unknown\x10\x00\x12\x06\n" +
	"\x02UP\x10\x01\x12\b\n" +
	"\x04DOWN\x10\x02\x12\v\n" +
	"\aCURRENT\x10\x032\x9f\x01\n" +
	"\x0fInternalService\x12?\n" +
	"\n" +
	"GetPayload\x12\x17.gnpb.GetPayloadRequest\x1a\x18.gnpb.GetPayloadResponse\x12K\n" +
	"\x0eLifecycleEvent\x12\x1b.gnpb.LifecycleEventRequest\x1a\x1c.gnpb.LifecycleEventResponseBH\n" +
	"\x14com.otorp.grpc.protoB\x0fGovernanceProtoH\x01P\x01Z\x1bgithub.com/forhsd/gnpb;gnpbb\x06proto3"

var (
	file_internal_proto_rawDescOnce sync.Once
	file_internal_proto_rawDescData []byte
)

func file_internal_proto_rawDescGZIP() []byte {
	file_internal_proto_rawDescOnce.Do(func() {
		file_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_rawDesc), len(file_internal_proto_rawDesc)))
	})
	return file_internal_proto_rawDescData
}

var file_internal_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_proto_goTypes = []any{
	(RunStatus)(0),                 // 0: gnpb.RunStatus
	(RelationType)(0),              // 1: gnpb.RelationType
	(*GetPayloadRequest)(nil),      // 2: gnpb.GetPayloadRequest
	(*GetPayloadResponse)(nil),     // 3: gnpb.GetPayloadResponse
	(*LifecycleEventRequest)(nil),  // 4: gnpb.LifecycleEventRequest
	(*LifecycleEventResponse)(nil), // 5: gnpb.LifecycleEventResponse
	(*RelationElement)(nil),        // 6: gnpb.RelationElement
	(*TableRelation)(nil),          // 7: gnpb.TableRelation
}
var file_internal_proto_depIdxs = []int32{
	0, // 0: gnpb.LifecycleEventRequest.run_status:type_name -> gnpb.RunStatus
	6, // 1: gnpb.TableRelation.sources:type_name -> gnpb.RelationElement
	6, // 2: gnpb.TableRelation.targets:type_name -> gnpb.RelationElement
	2, // 3: gnpb.InternalService.GetPayload:input_type -> gnpb.GetPayloadRequest
	4, // 4: gnpb.InternalService.LifecycleEvent:input_type -> gnpb.LifecycleEventRequest
	3, // 5: gnpb.InternalService.GetPayload:output_type -> gnpb.GetPayloadResponse
	5, // 6: gnpb.InternalService.LifecycleEvent:output_type -> gnpb.LifecycleEventResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_proto_init() }
func file_internal_proto_init() {
	if File_internal_proto != nil {
		return
	}
	file_internal_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_rawDesc), len(file_internal_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_goTypes,
		DependencyIndexes: file_internal_proto_depIdxs,
		EnumInfos:         file_internal_proto_enumTypes,
		MessageInfos:      file_internal_proto_msgTypes,
	}.Build()
	File_internal_proto = out.File
	file_internal_proto_goTypes = nil
	file_internal_proto_depIdxs = nil
}
